### ISSUE TITLE
Not an issue more a question

### ISSUE THREAD

**Issue by lucisac** [Attacktive/kvs-tools-csharp#14]
Hi there, was curious so tried running the python version you created, but I'm not sure what I need to edit in terms of paths to get it to make the mod file.  In any case, do you know if this version does or has any plans to support swapping original KVS files around for Blue Reflection SL?

**Comment by Attacktive** [comment]
Hello, @lucisac!

This C# version is incomplete for now; archiving process (.kvs → .ktsl2stbin) is not implemented yet.
With the Python version, you can extract *and* archive but I doubt *Blue Reflection SL* is supported. ☠️

You can still try:
1. `python kvs_extract.py <path/to/.ktsl2stbin/file>` to retrieve .kvs files,
2. make desired changes to them, then
3. `python kvs_archive.py </absolute/directory/path/to/kvs/files>`

I'll happily add support for other games like *Blue Reflection SL*, but it's going to take some time.
If you provide the .ktsl2stbin file, that should help!

**Comment by lucisac** [comment]
Hey bro.

Thanks for the reply.  Regarding the C# version (which I have no clue to use), no problem.  I was using the python (previously tried Hairo's exes) but I the python version I did not know what I'm supposed to edit in the PY file to make it work (result in a mod.xxx file being created) to be able to test it.  

What I wanted to do with the game was basic, extract all KVS (that worked-and could also make them ogg to know which songs they were), I then wanted to copy 3.kvs and replace it with 25 and 26.kvs, when I used Hairo's exe it made the ktsl2stbin file and the music played (all up to about where 25.kvs was), then other music after that was mute.

I will try no3 using that command where the swapped kvs files are and give it a go.  I had tried hex editing bits a pieces but no luck and it's a bit way over my head to be honest but was fun trying.

**Comment by lucisac** [comment]
Providing Sd00_BGM.ktsl2stbin file:  https://drive.google.com/file/d/1YFNNkzQZjaHc1TVu7PLlfjkt4w1c6Dl_/view?usp=sharing

**Comment by lucisac** [comment]
Providing ORIGINAL Sd00_BGM.ktsl2stbin file (previously shared the modded one sorry): https://drive.google.com/file/d/1PYJS2akoqaxCa4GzzChw-qRW0M6hN0UE/view?usp=sharing

**Comment by Attacktive** [comment]
Oops. I'm late. Yeah, my Python version is functionally no different from Hairo's. The missing support for the game has to be implemented.
I can't promise but I will some day.

Or, if you can do some hex editing, you can try one more thing.
Open the modified file and replace 2 chunks of bytes with those from the vanilla file:
- 12th to 16th byte (4 bytes)
- 64th to 96th byte (32 bytes)

**Comment by lucisac** [comment]
Ok will try that now and let you know.

**Comment by lucisac** [comment]
![image](https://user-images.githubusercontent.com/51527876/176598807-a0453f3c-f628-4dcc-9ee8-6cb26b4b280b.png)
I'm new to hex editing but sharing a screenshot of the edits.  Unfortunately it did not work.  Music from 1-24kvs still works but everything after 25+ broken (where I swapped the files)

**Comment by Attacktive** [comment]
I'm so sorry to hear that. I'm going to start working on it.
[This](https://store.steampowered.com/app/1423600/BLUE_REFLECTION_Second_Light) is the one, right?

**Comment by lucisac** [comment]
Yeah that's the game indeed.  Happy to test anything else to save you trouble.

**Comment by lucisac** [comment]
So exciting! You are such a generous and kind person to be working on this, thank you again.

**Comment by Attacktive** [comment]
No problem. It's fun to me, too. 😊
By the way, how do you test whether the archive is working correctly or not? Does clearing the game gives an option like BGM changer?

**Comment by lucisac** [comment]
No it does not.  The way I test is by replacing the battle music with no3.  Battle music is 25 I want to replace, and 26 is the battle music is becomes 3/4 later in the game.

No3 battle music (which is only used in some cutscenes only), you can listen here: https://www.youtube.com/watch?v=Na5QeYzIf1k

So to test you would just walk into a normal enemy in the field and if that music plays (got silence before), then it's working for sure.

**Comment by Attacktive** [comment]
Great. That makes sense. I think I can test it myself then.

**Comment by lucisac** [comment]
Indeed, although I am at your service if you need help, I can't recall how long it takes to even get to the first battle area as the game is story heavy, so there may be some school talking at the start.

**Comment by Attacktive** [comment]
Alright. I'll let you know if I need a hand.
Thanks!

**Comment by Attacktive** [comment]
@lucisac Man, I think I got it working.
Can you please test it?
I replaced #25 and #26 by #3 and it seems to work for me.

https://drive.google.com/file/d/18MbBSpgHDHQ5o6KQwd0Lif4xDo6UzG7C/view?usp=sharing

**Comment by lucisac** [comment]
Hi, I gave it a test as I'm later in my save I can only test 26, unfortunately the sound is blank.  Let me test a new game to check 25.

**Comment by lucisac** [comment]
OK, on a new game testing 25 does work perfect with the new theme, but 26 has no sound still hmm (later half game battle music), something must be up with that bit.  This is looking promising tho.

**Comment by Attacktive** [comment]
Duh. My bad. I tested 25 only. ☠️

> Fanfare music also blank (likely everything after 26 is broken - but 25 works good)
Nice! I can guess what is probably wrong.

**Comment by lucisac** [comment]
Yeah, it would take 25 hrs to get through the game enough to trigger the 2nd theme.  Can give a save file if you want but also don't want to spoil it, else I'm available all day.

**Comment by Attacktive** [comment]
Hmm. I'm not sure how long it's gonna take to fix it. A save file will be better. 😊
Thanks.

**Comment by lucisac** [comment]
Ok try this. https://drive.google.com/file/d/1EeWAubVCSnY3zfC3M-kHnds58X_g9-h0/view?usp=sharing

Copy to documents folder
KoeiTecmo\BLUE REFLECTION Second Light\GameData03\

**Comment by Attacktive** [comment]
Oops. It requires DLCs to load. xD
Did you get the *Digital Deluxe Edition* or the *Ultimate* one?

**Comment by lucisac** [comment]
Oh really damm, it's the ultimate.  Hmm, well actually there's another way to test, like after you win a battle, if it plays the victory music then 26 will likely work too.

**Comment by lucisac** [comment]
27.kvs is the victory music that plays the same after both 25 and 26 respectively no matter where you are in the game.

**Comment by lucisac** [comment]
https://drive.google.com/file/d/17B04QWFXHR3iprV6huUeU3TeFCxg4uN1/view?usp=sharing

**Comment by lucisac** [comment]
I was inside hidden island in that save, now I resaved at the school maybe it will work idk?
https://drive.google.com/file/d/1XtIwsYxXvRKQ3-Rkm6xisTYszYo12L10/view?usp=sharing

**Comment by lucisac** [comment]
And this is the data.dat inside y systemdata folder in case you need this too. (rename to data.dat put in systemdata folder)
https://drive.google.com/file/d/1zYLYRARZwBmdYc0G3rnay66Y-AnMYW3Z/view?usp=sharing

**Comment by Attacktive** [comment]
> Oh really damm, it's the ultimate. Hmm, well actually there's another way to test, like after you win a battle, if it plays the victory music then 26 will likely work too.

Yeah, I tried replacing the very first one and no music plays. It's easier to test now.
Thank you!

**Comment by Attacktive** [comment]
Turns out that in order to change a track, the .ktsl2asbin file must be changed as well but I don't really know how. It's just another different file format.
There's a few pieces of information about .ktsl2asbin [out there](https://github.com/three-houses-research-team/010-binary-templates/blob/master/KTSR.bt), but I don't think I can take care of it in the near future.

I'm sorry. 😭
I appreciate your contribution, though.

**Comment by lucisac** [comment]
Ahh damm, although you did manage to change 25 and everything below (1-24) also still worked.  I'm not sure what you did exactly but I'll do a comparison and tinker with it.  Thanks for all your help!

**Comment by Attacktive** [comment]
ktsl2asbin has info of the position (within the .ktsl2stbin) of each sound track.
Because track ＃25 is replaced by ＃3 and ＃3 is smaller than original ＃25, the positions after ＃25 have to change.

I tried that but it didn't work; may there's something else I must handle. 💀

**Comment by lucisac** [comment]
Ahh okay that makes sense.  These files are looped though right, so wondering if there's a way to trick it maybe like add 0s or something, I'm looking at your file now to see how you even got 25 working (is already beyond me).

**Comment by Attacktive** [comment]
Well, there's some bytes dedicated to *Blue Reflection* at the very beginning of the file, up to `0x3f`. I kept it as is.
From `0x40`, I simply appended the content of the extracted files.

**Comment by lucisac** [comment]
Ahh I see just now I worked it out.  Even with the original Hairo archive 25 works.  So then what you say may be correct, although 3.kvs is smaller than both 25 and 26, I'll see if I can insert dummy bytes maybe? I would have to do this after 25 and 26 somehow.

**Comment by Attacktive** [comment]
Hmmm. I don't know about kvs or ogg format so I'm not sure.

**Comment by lucisac** [comment]
Thanks heaps man for looking into it, I'm very appreciative of your hard work and time.

**Comment by lucisac** [comment]
Dude I did it! (thx to u).  I just added dots!  Damm I was like this is 1 in 100 chance it gonna work lol Not sure if it will break the loops so I'll let it run through in game see how it sounds.

Link: https://drive.google.com/file/d/1PYJS2akoqaxCa4GzzChw-qRW0M6hN0UE/view?usp=sharing

**Comment by Attacktive** [comment]
Hey congrats! So padding works!

**Comment by lucisac** [comment]
Yeah man it's looping fine we can celebrate! Can I tip you for your work?

**Comment by Attacktive** [comment]
Nonono no worries. I did have fun too. 😊
Thank YOU.

**Comment by lucisac** [comment]
You are a superstar, I wish you good fortune!

**Comment by Attacktive** [comment]
Same to you mate.

**Comment by lucisac** [comment]
Sure gimme 30 mins

Sent from my iPhone

On 2 Jul 2022, at 1:32 pm, Attacktive ***@***.***> wrote:

﻿

@lucisac<https://github.com/lucisac> Man, I think I got it working.
Can you please test it?
I replaced #25 and #26 by #3<https://github.com/Attacktive/kvs-tools-csharp/pull/3> and it seems to work for me.

https://drive.google.com/file/d/18MbBSpgHDHQ5o6KQwd0Lif4xDo6UzG7C/view?usp=sharing
